name: build-lint

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - "*"
    paths:
      - "!**"
      - "Dockerfile"
      - "docker-bake.hcl"
      - "tools/**/**"
      - "scripts/**/**"
      - ".github/**/**"
      - "Makefile"

jobs:
  lint-dockerfiles:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        dockerfile:
          [
            "Dockerfile",
          ]
    runs-on: "ubuntu-24.04"
    name: Lint ${{ matrix.dockerfile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Lint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: ${{ matrix.dockerfile }}
          annotate: true
          error_level: 2

  check-release-config:
    runs-on: 'ubuntu-24.04'
    name: Check releaser configs
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.25.x

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Check release
        run: |
          make check-releaser
        shell: bash

  build:
    needs: [ lint-dockerfiles, check-release-config ]
    name: Build
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'linux/arm64,linux/amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build Docker image
        uses: docker/bake-action@v6.8.0
        env:
          TAGS: ${{ steps.meta.outputs.bake-file-tags }}
          LABELS: ${{ steps.meta.outputs.bake-file-labels }}
          ANNOTATIONS: ${{ steps.meta.outputs.bake-file-annotations }}
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ env.TAGS }}
            cwd://${{ env.LABELS }}
            cwd://${{ env.ANNOTATIONS }}
          push: false
          pull: true

